---
APPLY_FIXES: all

ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - BASH
  - ENV
  - KUBERNETES
  - COPYPASTE
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - SPELL_CSPELL
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - MDLINKCHECK_LINKCHECK

YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: (packages/*|bundles/*)

MARKDOWN_DEFAULT_STYLE: markdownlint
MARKDOWN_MARKDOWNLINT_FILE_EXTENSIONS: [".md"]
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yaml

SPELL_CSPELL_DISABLE_ERRORS: true
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PARALLEL: true
GITHUB_STATUS_REPORTER: true
VALIDATE_ALL_CODEBASE: true
LOG_LEVEL: WARNING
MARKDOWN_MARKDOWN_LINK_CHECK_ARGUMENTS: "-q"
DISABLE_ERRORS: true
PLUGINS:
  - https://raw.githubusercontent.com/shiranr/linkcheck/v2.0.17.beta/mega-linter-plugin-linkcheck/linkcheck.megalinter-descriptor.yml
