---
branches:
  - name: release
  - name: "release-+([0-9])?(.{+([0-9]),x}).x"
    channel: ""
    range: '${name.replace(/^release-/g, "")}'
  - name: main
    prerelease: alpha
    channel: ""
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - {type: fix, release: patch}
        - {type: feat, release: major}
  - "@semantic-release/github"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogTitle: "# Changelog"
  - - "@semantic-release/git"
    - assets: [CHANGELOG.md]
preset: conventionalcommits
presetConfig:
  types:
    - {type: feat, section: Features}
    - {type: fix, section: Bug Fixes}
    - {type: ci, section: Other Changes}
    - {type: perf, section: Other Changes}
    - {type: refactor, section: Other Changes}
    - {type: docs, section: Other Changes}
    - {type: chore, hidden: true}
    - {type: style, hidden: true}
    - {type: test, hidden: true}
