---
no_progress: true
package:
  create:
    set:
      PACKAGE_VERSION: 1.0.0
      NVIDIA_CHART_REPO: https://helm.ngc.nvidia.com/nvidia/
      NVIDIA_GPU_OPERATOR_CHART_VERSION: v23.9.1
      NVIDIA_GPU_OPERATOR_VERSION: v23.6.2
      NVIDIA_GPU_DRIVER_VERSION: 535-5.15.0
      NVIDIA_GPU_FEATURE_DISCOVERY_VERSION: v0.8.2
      NVIDIA_CUDA_VERSION: 12.3.1
      NVIDIA_CONTAINER_TOOLKIT: v1.14.4
      NVIDIA_KUBERNETES_DEVICE_PLUGIN_VERSION: v0.14.4
      NVIDIA_MIG_MANAGER: v0.5.5
      NVIDIA_GPU_VALIDATOR: v23.6.2
      NVIDIA_DCGM: 3.3.3-1
      NVIDIA_DCGM_EXPORTER: 3.3.3-3.3.1
      NVIDIA_DRIVER_MANAGER: v0.6.5
      NVIDIA_VGPU_DEVICE_MANAGER: v0.2.4
