---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  deps.rockylinux8:
    desc: "Creates a local RPM Repository for Rocky Linux 8"
    dir: "rpm"
    cmds:
      - mkdir -p rockylinux8
      - >
        docker run -it --rm -v "$(pwd)/rockylinux8:/opt/rpms" --platform linux/amd64 rockylinux:8 /bin/bash -c "
          yum update -y && yum install -y createrepo dnf dnf-plugins-core findutils;
          dnf makecache;
          dev_packages=(\$(dnf group info 'Development Tools' | grep -oP '(?<=^   ).*'));
          sync_packages=(\$(dnf distro-sync --assumeno 2>&1 | grep -oP '(?<=Upgrade  ).*(?=  -  )'));
          packages=('kernel-devel' 'kernel-headers' 'gcc' 'make' 'git' 'elfutils-libelf' 'elfutils-libelf-devel' \${dev_packages[@]} \${sync_packages[@]});
          for package in \${packages[@]}; do
              dnf install --downloadonly --downloaddir=/opt/rpms \$package -y;
          done;
          for package in \${packages[@]}; do
              dnf repoquery --requires --resolve \$package | xargs -r dnf install --downloadonly --downloaddir=/opt/rpms -y;
          done;
          createrepo --database /opt/rpms;
          ls -la /opt/rpms;
        "
      - tar -czf rockylinux8.tar.gz -C rockylinux8 .
      - find . -type f ! -name '*.tar.gz' -delete
      - find . -depth -type d -empty -delete
  test.rockylinux8:
    desc: "Extracts the tarball, sets up a local repo, and installs the packages"
    cmds:
      - >
        docker run -it --rm -v "${PWD}/rpm:/opt/rpms" --platform linux/amd64 rockylinux:8 /bin/bash -c "
          tar -xzf /opt/rpms/rockylinux8.tar.gz -C /opt/rpms;
          echo -e '[local]\nname=Local Repo\nbaseurl=file:///opt/rpms\nenabled=1\ngpgcheck=0' > /etc/yum.repos.d/local.repo;
          yum clean all;
          yum makecache;
          packages=('kernel-devel' 'kernel-headers' 'gcc' 'make');
          for package in \${packages[@]}; do
              yum install --disablerepo='*' --enablerepo='local' \$package -y;
          done;
        "
